########################################
#
# rootfs
#
########################################

ifdef CONFIG_BUSYBOX_ROOT_FS
include fs/busybox/Makefile
endif

ifdef CONFIG_BUILD_ROOT_FS
include fs/buildroot/Makefile
endif
