##
## make.inc
##
## History:
##    2024/11/29 - [yinwg] Created file
##
## 	This program is free software; you can redistribute it and/r modify
##  it under the terms of the GNU General Public License version 2 as
##  published by the Free Software Foundation.
##
##########################################################################################################


###########################################################################################################
#	build local linux driver
###########################################################################################################

LOCAL_PATH	:= $(call my-dir)
include $(LOCAL_PATH)/Makefile
